services:

  web:
    image: shibilbasith11/two-tier-todo:latest
    container_name: todo-web
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: todo-db
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
