services:
  app:
    build:
      context: .
    container_name: todo-app
    restart: always
    ports:
      - "8000:8000"
    networks:
      - app-net
    depends_on:
      - db
    environment:
      HOST: db
    command:

  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - app-net
    volumes:
      - app-vol:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
volumes:
  app-vol:
networks:
  app-net:
